name = "UHope"
license = "MIT"
description = "UHope"
homepage = "https://uhopecommuity.org/"
demosite = "https://uhopecommunity.org/"
tags = ['non-profit', 'business', 'uhope', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'dark', 'creative', 'contact-form', 'custom-themes', 'mobile', 'flexbox', 'minimalistic', 'gethugothemes']
min_version = "1.0"

[author]
  name = "JC"
  homepage = ""
